### ISSUE TITLE
Request for Code for Data Splitting of Sun397 Dataset

### ISSUE THREAD

**Issue by lygzboy** [JunyiZhu-AI/confidence_aware_PFL#1]
Thank you for sharing the code for this very interesting work.

I tried to reproduce your Sun397 experiment, but found the data splitting to be challenging. Could you please provide the corresponding code for data splitting?

We apologize for any inconvenience caused. Thank you for your cooperation.

**Comment by JunyiZhu-AI** [comment]
Thank you for your interest in our work and for reaching out with your question.

I understand that data splitting for the Sun397 experiment can be quite challenging. To assist you, I've uploaded the preprocessing and data splitting scripts to the *utils* folder in our repository. These scripts should provide a clear understanding of the data splitting process we used.

Please note that while the dataloader has not been fully integrated into the training script due to time constraints for additional cleanup and checks. However, the provided scripts should still significantly ease the process for you.
